### ISSUE TITLE
Confusing duplicate

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10.Validation#1]
Hey @ArtjomP could you hide your library from Nuget?

**Comment by ArtjomP** [comment]
Done.
Unfortunately ValidateableModelBase is not inherited from ViewModelBase. I used it as ViewModelBase in my project. I'll try to change my way.

**Comment by JerryNixon** [comment]
Now I see why we had such a mix up between us on the name of that class. By the way, I want to thank you for the time you put into this library. I think it was almost ready when you started playing with it and the effort you put in really made it valuable for the developer community interested in validation. Thank you again.
