### ISSUE TITLE
Validating across multiple PivotItems

### ISSUE THREAD

**Issue by gandhibobandhi** [Windows-XAML/Template10.Validation#14]
Hi guys,

I'm quite new to the UWP scene so please bear with me, I may be getting everything backwards. I seem to be having a problem using the ControlWrapper on multiple different Pivot Items in a Pivot. The first tab shows correctly, but the controls on all the subsequent tabs have the red validation marker next to them and an empty error message.

If I shuffle the tabs around and try again, validation only works on whatever tab happens to be first. However, sometimes after several seconds, it seems the validation on some tabs spontaneously starts working again.

It's probably also worth mentioning that the contents of each of my PivotItems is a UserControl, which contains the controls I'm validating against. Also, please find attached some relevant code from my solution: [PivotValidation.zip](https://github.com/Windows-XAML/Template10.Validation/files/1124038/PivotValidation.zip)

**Comment by JerryNixon** [comment]
This is the behavior of the Pivot. It lazy-loads pivot items.
