### ISSUE TITLE
an issue with Entity Framework Core?

### ISSUE THREAD

**Issue by TavoGL** [Windows-XAML/Template10.Validation#3]
I'm getting this error with the model.

![captura de pantalla 6](https://cloud.githubusercontent.com/assets/15368343/18476483/d90d9a92-798f-11e6-86ae-ad8c8553ab48.png)

**Comment by TavoGL** [comment]
And besides this can be very useful. Thanks for contributing to the community.

**Comment by mvermef** [comment]
yes, it tries to create shadow properties for the properties that are associated with the ValidatableModelBase, solution is to use a DTO for your models that require Input validation for now.

**Comment by JerryNixon** [comment]
Incompatible properties will need to be standard `{ get; set; }` properties. You can mix and match them in your project. That's fine. But it is up to you to track them.

**Comment by mvermef** [comment]
no it won't matter... it tries to create columns in the table based on properties in the base class in this case ValidatableModelBase is the issue, due to "Properties", "IsValid", etc....  You can try ignore() but it doesn't seem to help.
