### ISSUE TITLE
Have to use static field width when wrapped with ControlWrapper

### ISSUE THREAD

**Issue by Robzilla** [Windows-XAML/Template10.Validation#6]
Hi all

I would like to use the HorizontalAlignment property to be set to stretch on a TextBox which is wrapped by the Validation ControlWrapper control. But is seems that the wrapper eats this setting and a static resource of type Double is required to set a different field width. Any thoughts Jerry?

**Comment by JerryNixon** [comment]
What's the problem?

**Comment by Robzilla** [comment]
I was hoping to dynamically resize the field based on the rendered size of the parent control, rather then a fixed width. This would allow a more responsive GUI given UWP apps are supposed to run on multiple form factors.

**Comment by JerryNixon** [comment]
Just use MaxWidth
