### ISSUE TITLE
Controls inside validation ControlWrapper cause error

### ISSUE THREAD

**Issue by IsmajlMaliqi** [Windows-XAML/Template10.Validation#8]
Hi,

I'm having an issue while using Template10 validation, actually if I put a control (texbox)
inside control wrapper like it should be, I got an error on design mode like this,

**COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.**
StackTrace
   at System.Runtime.InteropServices.WindowsRuntime.IVector`1.InsertAt(UInt32 index, T value)
   at System.Runtime.InteropServices.WindowsRuntime.VectorToListAdapter.InsertAtHelper[T](IVector`1 _this, UInt32 index, T item)
   at System.Runtime.InteropServices.WindowsRuntime.VectorToListAdapter.Insert[T](Int32 index, T item)
**InnerException: None**

Application could run normally, but controls are disappearing.

Please could someone got me on track of this issue!?

**Comment by Chris-Marassovich** [comment]
Hi @IsmajlMaliqi,

You are not alone.  I also have the exact same issue as you.
In my case I only needed to validate a single field so I implemented my own error indicator and binding it's visibility to the validation error collection.

I know this is no help to you at all except to be aware that you are not the only one with the issue.  :-)

Regards
Chris ...

**Comment by IsmajlMaliqi** [comment]
Hey @Chris-Marassovich,
thank you for your respond, 
actually digging deeper, I noticed changing target (solution platform, from x86, to x64) got it worked,
but this is not what should be the solution of the problem and probably @JerryNixon must be aware of!

Tank you all!
Isa.

**Comment by Chris-Marassovich** [comment]
@IsmajlMaliqi 
Good spot that changing the target to x64 helps the designer to not raise an error .. but in my case it does not change the fact at runtime it causes a crash. :-)

Cheers
Chris ...

**Comment by JerryNixon** [comment]
Can't be sure, think it has to do with references, you might try the new ValidationBehavior
