### ISSUE TITLE
IsDirty property on class never changes from False value?

### ISSUE THREAD

**Issue by Chris-Marassovich** [Windows-XAML/Template10.Validation#9]
Hello T10 team,

I just started to use the Nuget validation package in my app and I am noting that the IsDirty property on the class never changes from False.
The doco does not state exactly what this property does so here is my assumption.
I assume it tracks if any data has been changed in your class. I think the use of this would be in say your Save command on the CanExecute side you can look at the IsDirty and IsValid properties.  This means you only light up the Save button when the user has modified some data and it also passes your validation rules.

That is how I assume IsDirty works.  Looking at the IsDirty property on the class it never changes from False.  I can see my IsValid on the class change as my validation logic is tested.

Is my assumption on how the IsDirty is meant to work correct and any idea's on why it is not working as expected?  A quick look at the Class implementation of the IsDirty property and I cannot see how it is bound to the many properties IsDirty of the fields in the class?  

Cheers
Chris ....

**Comment by IsmajlMaliqi** [comment]
Hi @Chris-Marassovich 
As I understood the **IsDirty** working is, the first/last value of the property is changed to the new one, 
so on start-up, the first value of the property is = "", and you change it to the new one like = "hello",
the **IsDirty** changes to the true value, and the **OriginalValue** stays to= "".

However, the whole scenario is for example, if you have an object obj1 with properties like **prop1** and **prop2**, 
and at the initializing **ob1** = _new_ **obj1()** { **prop1** = “”, **prop2**=””}, optionally **Validate()** it on startup.
And the process follows, if you change value for **prop1** or **prop2**, the **IsDirty** property changes to = true for each changed property, and the **OriginalValue** stays =””, like old one in this case.
So the **IsDirty** property is not changed for **obje1** itself unless you do not bind-it or change it programmatically.

Hope this could help you!

Regards, 
Isa.

**Comment by Chris-Marassovich** [comment]
@IsmajlMaliqi 
Are you saying that it is my responsibility, using your example above, that I must monitor prop1 and prop2 for changes and set IsDirty on obj1 myself?

Mmm that does not follow the pattern for IsValid.  Changes to IsValid on prop1 and prop2 flow up to IsValid on obj1.

My gut feeling and reading of the code is that the IsDirty class property is not quite implemented yet.  :-( note I am not a skilled C# dev so please take my last comment as such.

Cheers
Chris ...

**Comment by mvermef** [comment]
for what it is where here is one of his original posts using this method of validation in Windows 8.1 before it was slightly modified for UWP

http://blog.jerrynixon.com/2014/07/lets-code-handling-validation-in-your.html

**Comment by JerryNixon** [comment]
Thanks @Chris-Marassovich. Real bug. Fixed in repo.
